name: Deploy Alismitch Website to GitHub Pages

on:
  push:
    branches:
      - main   # Trigger deployment when you push to main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the project (Vite outputs to dist/)
      - name: Build project
        run: npm run build

      # 5. Deploy dist/ to alismitch-deploy branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: alismitch-deploy   # 🔹 Custom branch name
          publish_dir: ./dist
